dist: bionic

branches:
  only:
  - master
 
language: minimal

services:
  - docker

before_install:
  - sudo add-apt-repository -y ppa:chombourger/ppa
  - sudo apt-get update && sudo apt-get install -y podman user-mode-linux
  - python3 modules/seine/seine build test.yaml
