dist: bionic

branches:
  only:
  - master
 
language: minimal

services:
  - docker

before_install:
  - sudo add-apt-repository -y ppa:chombourger/ppa
  - sudo apt-get update && sudo apt-get install -y podman python3-pip user-mode-linux
  - pip3 install avocado-framework
  - python3 ./seine.py build -v examples/pc-image/pc-image.yaml
  - avocado run tests/*/*.py
