# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0

import os
import re
import shutil
import stat
import tarfile
import tempfile

import guestfs

from seine.bootloader        import detect as detect_bootloader
from seine.imager_appliance import ImagerAppliance
from seine.imager_kernel    import ImagerKernel
from seine.imager_extra_tools import ExtraImagerTools
from seine.packages          import FALLBACK_EPOCH
from seine.partition        import RO_FSTYPES
from seine.partition        import VERITY_HASH_TYPE
from seine.tasks import Task
from seine.kernel.uki        import ukify_argv
from seine.container import ContainerEngine
from seine.utils            import HOST_ARCH

DEVICE = "/dev/sda"

# squashfs/erofs are not g.mkfs() targets, so RO_FSTYPES mounts are
# staged as this and replaced later (see create()'s finalize pass).
STAGING_TYPE = "ext4"

# GPT partition type GUIDs.
GPT_TYPE_ESP = "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
GPT_TYPE_LVM = "E6D6D379-F507-44C2-A23C-238F2A3DF928"
GPT_TYPE_XBOOTLDR = "BC13C2FF-59E6-4262-A352-B275FD6F7172"

# DPS: root and '/usr' GUIDs are arch-specific (auto-discovery must not
# pick the wrong kernel's root on a mixed-arch disk); '/var', '/var/tmp',
# '/home', '/srv' are universal. Keyed by 'distribution: architecture:'.
GPT_TYPE_ROOT = {
    "amd64": "4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709",
    "arm64": "B921B045-1DF0-41C3-AF44-4C6F280D3FAE",
    "armhf": "69DAD710-2CE4-4E3C-B16C-21A1D49ABED3",
    "i386":  "44479540-F297-41B2-9AF7-D131D5F0458A",
}
GPT_TYPE_USR = {
    "amd64": "8484680C-9521-48C6-9C11-B0720656F69E",
    "arm64": "B0E01050-EE5F-4390-949A-9101B17104E9",
    "armhf": "7D0359A3-02B3-4F0A-865C-654403E70625",
    "i386":  "75250D76-8CC6-458E-BD66-BD47CC81A812",
}
GPT_TYPE_VAR = "4D21B016-B534-45C2-A9FB-5C16E091FD2D"
GPT_TYPE_VAR_TMP = "7EC6F557-3BC5-4ACA-B293-16EF5DF639D1"
GPT_TYPE_HOME = "933AC7E1-2EB4-4F13-B844-0E14E2AEF915"
GPT_TYPE_SRV = "3B8F8425-20E0-4F3B-907F-1A25A76F98E8"

# DPS verity GUIDs for root/'/usr', the only mountpoints it defines.
# No signature partition or cmdline roothash= yet: _build_verity() sets
# each pair's GPT GUID to the root hash's two halves instead (systemd-repart's scheme).
GPT_TYPE_ROOT_VERITY = {
    "amd64": "2C7357ED-EBD2-46D9-AEC1-23D437EC2BF5",
    "arm64": "DF3300CE-D69F-4C92-978C-9BFB0F38D820",
    "armhf": "7386CDF2-203C-47A9-A498-F2ECCE45A2D6",
    "i386":  "D13C5D3B-B5D1-422A-B29F-9454FDC89D76",
}
GPT_TYPE_USR_VERITY = {
    "amd64": "77FF5F63-E7B6-4633-ACF4-1565B864C0E6",
    "arm64": "6E11A4E7-FBCA-4DED-B9E9-E1A512BB664E",
    "armhf": "C215D751-7BCD-4649-BE90-6627490A4C05",
    "i386":  "8F461B0D-14EE-4E81-9AA9-049B6FB97ABD",
}

# Fallback hypervisor per arch, used when cross-building and 'imager:
# hypervisor:' is unset (guestfs would otherwise launch its host-arch qemu).
DEFAULT_HYPERVISORS = {
    "amd64": "/usr/bin/qemu-system-x86_64",
    "arm64": "/usr/bin/qemu-system-aarch64",
    "armhf": "/usr/bin/qemu-system-arm",
    "i386":  "/usr/bin/qemu-system-i386",
}

# libguestfs hardcodes x86-only qemu flags (machine, cpu, console) for any
# hypervisor, with no override for some of them. Confirmed for arm64 only,
# via a real cross-arch build.
CROSS_ARCH_QEMU_FIXUPS = {
    "arm64": {"machine": "virt,accel=tcg", "cpu": "max", "console": "ttyAMA0"},
}

QEMU_WRAPPER_SCRIPT = """#!/bin/bash
# generated by seine -- fixes up qemu flags libguestfs hardcodes for
# x86, then execs the real hypervisor.
args=()
while [ $# -gt 0 ]; do
    case "$1" in
        -global)
            if [ "$2" = "virtio-blk-pci.scsi=off" ]; then
                shift 2
                continue
            fi
            ;;
        -machine)
            args+=("-machine" "{machine}")
            shift 2
            continue
            ;;
        -cpu)
            args+=("-cpu" "{cpu}")
            shift 2
            continue
            ;;
        -append)
            args+=("-append" "${{2/console=ttyS0/console={console}}}")
            shift 2
            continue
            ;;
    esac
    args+=("$1")
    shift
done
exec "{real_hv}" "${{args[@]}}"
"""

# Hooks around g.launch()'s real fork(), no-op for CLI builds. The TUI's
# _wire_launch_guard() (seine/tui/target.py) uses these to disconnect and
# reconnect its live mtda connection, whose threads would otherwise stall the fork.
before_launch = lambda: None
after_launch = lambda: None

class Imager:
    def __init__(self, source):
        self.source = source
        self.keep = source.options["keep"]
        self.verbose = source.options["verbose"]

    # Keeps only entries for files that made it into the tarball: getfattr
    # walked the live container filesystem, which still had packages later
    # removed before export.
    def _filter_xattr_dump(self, text, known_files):
        blocks = []
        current = []
        keep = False
        for line in text.splitlines():
            if line.startswith("# file: "):
                if keep and current:
                    blocks.append("\n".join(current))
                current = [line]
                keep = line[len("# file: "):] in known_files
            elif keep:
                current.append(line)
        if keep and current:
            blocks.append("\n".join(current))
        return "\n\n".join(blocks) + "\n"

    def _restore_xattrs(self, g, tarball):
        with tarfile.open(tarball) as tar:
            known_files = set()
            xattr_member = None
            for member in tar.getmembers():
                if member.name == "rootfs.xattr":
                    xattr_member = member
                    continue
                if member.issym() or member.isdir():
                    continue
                known_files.add(member.name)
            if xattr_member is None:
                return
            dump = tar.extractfile(xattr_member).read().decode()

        if not g.is_file("/usr/bin/setfattr"):
            print("  note: 'attr' is not installed in the target image, "
                  "skipping restore of extended attributes (e.g. file capabilities)")
            return

        # Xattr values can hold NULs, which a Python str can't carry to the
        # setxattr API -- upload the dump instead and let setfattr --restore
        # apply it.
        filtered = self._filter_xattr_dump(dump, known_files)
        g.write("/rootfs.xattr", filtered.encode())
        g.sh("setfattr --restore=/rootfs.xattr")
        g.rm("/rootfs.xattr")

    def _mkfs(self, g, part, dev):
        fstype = STAGING_TYPE if part["type"] in RO_FSTYPES else part["type"]
        g.mkfs(fstype, dev)
        if "label" in part:
            g.set_label(dev, part["label"])

    # DPS role GUID for a plain (non-ESP/LVM/XBOOTLDR) partition.
    # 'None' means no DPS role -- parted keeps its generic default GUID.
    DPS_UNIVERSAL_ROLES = {
        "/var/":      GPT_TYPE_VAR,
        "/var/tmp/":  GPT_TYPE_VAR_TMP,
        "/home/":     GPT_TYPE_HOME,
        "/srv/":      GPT_TYPE_SRV,
    }

    def _dps_gpt_type(self, part, target_arch, partitions_by_label):
        if part.get("type") == VERITY_HASH_TYPE:
            data = partitions_by_label[part["verity-for"]]
            roles = GPT_TYPE_ROOT_VERITY if data["_prefix"] == "/" else GPT_TYPE_USR_VERITY
            return roles.get(target_arch)
        prefix = part.get("_prefix")
        if prefix == "/":
            return GPT_TYPE_ROOT.get(target_arch)
        if prefix == "/usr/":
            return GPT_TYPE_USR.get(target_arch)
        return self.DPS_UNIVERSAL_ROLES.get(prefix)

    def _partition_device(self, g, table, part, index, target_arch, partitions_by_label):
        start_sect = part["_start_mib"] * 2048
        end_sect = part["_end_mib"] * 2048 - 1
        flags = part.get("flags", [])
        prlogex = "primary"
        if table == "msdos":
            if "extended" in flags:
                prlogex = "extended"
            if "logical" in flags:
                prlogex = "logical"
        g.part_add(DEVICE, prlogex, start_sect, end_sect)
        if table == "gpt":
            g.part_set_name(DEVICE, index, part["label"])
            if "boot" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_ESP)
            elif "lvm" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_LVM)
            elif "xbootldr" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_XBOOTLDR)
            else:
                dps_type = self._dps_gpt_type(part, target_arch, partitions_by_label)
                if dps_type is not None:
                    g.part_set_gpt_type(DEVICE, index, dps_type)
        elif "boot" in flags:
            g.part_set_bootable(DEVICE, index, True)
        return DEVICE + str(index)

    # 'm' must be a physical partition (in 'part_index') -- LVM volumes have
    # no GPT entry to read a PARTUUID from. Lower-cased to match udev's
    # by-partuuid symlinks.
    def _partuuid(self, g, part_index, m):
        return g.part_get_gpt_guid(DEVICE, part_index[id(m)]).lower()

    def _write_fstab(self, g, mount_order, mount_devices, part_index):
        fstab = []
        for m in mount_order:
            # Verity mounts come from systemd-veritysetup-generator + gpt-auto
            # (see _build_verity()), not fstab -- an entry here would mount
            # the raw, unverified partition.
            if m.get("verity"):
                continue
            dev = mount_devices[id(m)]
            ro = m["type"] in RO_FSTYPES
            if m["_lvm"]:
                what = dev
            elif ro and m.get("identify") == "partuuid":
                what = "PARTUUID=%s" % self._partuuid(g, part_index, m)
            elif ro:
                what = "PARTLABEL=%s" % m["label"]
            else:
                what = "UUID=%s" % g.vfs_uuid(dev)
            options = "defaults"
            passno = 2
            if ro:
                options = "ro"
                passno = 0
            elif m["_prefix"] == "/":
                if m["type"] != "btrfs":
                    options = "errors=remount-ro"
                passno = 1
            elif m["type"] == "vfat":
                options = "umask=0077"
            fstab.append("%s %s %s %s 0 %d" % (what, m["_prefix"], m["type"], options, passno))
        g.write("/etc/fstab", ("\n".join(fstab) + "\n").encode())

    def _label_selinux(self, g, mount_order):
        se_contexts = "/etc/selinux/default/contexts/files/file_contexts"
        if not (g.is_file(se_contexts) and g.is_file("/usr/sbin/setfiles")):
            return
        print("Setting file contexts for SELinux...")
        if g.is_file("/etc/default/grub"):
            grub_cfg = g.read_file("/etc/default/grub").decode()
            grub_cfg = re.sub(r'^(GRUB_CMDLINE_LINUX=.*)"$', r'\1 security=selinux"',
                               grub_cfg, flags=re.MULTILINE)
            g.write("/etc/default/grub", grub_cfg.encode())
        # setfiles doesn't cross filesystem boundaries, so run it per mount.
        # Skip FAT, which has no xattr support.
        for m in mount_order:
            if m["type"] in ("vfat", "msdos", "fat", "fat32"):
                continue
            g.sh("setfiles -m%s %s %s" % (
                " -v" if self.verbose else "", se_contexts, m["_prefix"]))

    # 'None' means no kernel -- not every 'multiconfig:' group needs one.
    # More than one kernel/initrd is an error, not a silent pick.
    def _boot_files(self, g):
        entries = g.ls("/boot") if g.is_dir("/boot") else []
        kernels = sorted(e for e in entries if e.startswith("vmlinuz-"))
        initrds = sorted(e for e in entries if e.startswith("initrd.img-"))
        if not kernels and not initrds:
            return None
        if len(kernels) != 1 or len(initrds) != 1:
            raise RuntimeError(
                "expected exactly one kernel and one initrd under '/boot', "
                "found %d kernel(s) and %d initrd(s) (%s)"
                % (len(kernels), len(initrds), ", ".join(entries)))
        return "/boot/%s" % kernels[0], "/boot/%s" % initrds[0]

    # Per-group entries are written directly, not by 'update-grub', so read
    # the cmdline it would otherwise fold into the 'linux' line ourselves.
    def _grub_cmdline(self, g):
        if not g.is_file("/etc/default/grub"):
            return ""
        conf = g.read_file("/etc/default/grub").decode()
        parts = []
        for name in ("GRUB_CMDLINE_LINUX_DEFAULT", "GRUB_CMDLINE_LINUX"):
            m = re.search(r'^%s="(.*)"' % name, conf, re.MULTILINE)
            if m and m.group(1).strip():
                parts.append(m.group(1).strip())
        return " ".join(parts)

    # systemd-repart's scheme: a verity pair's root hash is its two GPT
    # GUIDs concatenated (data = high 128 bits, hash = low 128). Not
    # authentication alone -- pinning it needs a signed UKI (kernel/uki.py).
    def _hex_to_gpt_guid(self, hexstr):
        return "%s-%s-%s-%s-%s" % (
            hexstr[0:8], hexstr[8:12], hexstr[12:16], hexstr[16:20], hexstr[20:32])

    # Runs before 'hp's partition is written -- the root hash decides both
    # GUIDs. squashfs (unlike erofs) doesn't pad to veritysetup's 4096-byte
    # blocks, so pad here.
    def _build_verity(self, g, tools_dir, m, scratch, hp, part_index):
        print("Building verity hash tree for '%s'..." % m["label"])
        block_size = 4096
        size = g.filesize(scratch)
        aligned = -(-size // block_size) * block_size
        if aligned != size:
            g.truncate_size(scratch, aligned)

        run = "LD_LIBRARY_PATH=%s %s/veritysetup" % (tools_dir, tools_dir)
        hash_scratch = "/%s.verity.img" % hp["label"]
        roothash_file = "/%s.roothash" % hp["label"]
        g.sh("%s format --root-hash-file=%s %s %s"
             % (run, roothash_file, scratch, hash_scratch))
        roothash = g.read_file(roothash_file).decode().strip()
        g.rm(roothash_file)
        if len(roothash) != 64:
            raise RuntimeError(
                "'veritysetup format' for '%s' produced a %d-hex-digit root "
                "hash, expected 64 (sha256) -- only the default hash "
                "algorithm is supported" % (m["label"], len(roothash)))

        data_guid = self._hex_to_gpt_guid(roothash[0:32])
        hash_guid = self._hex_to_gpt_guid(roothash[32:64])
        g.part_set_gpt_guid(DEVICE, part_index[id(m)], data_guid)
        g.part_set_gpt_guid(DEVICE, part_index[id(hp)], hash_guid)

        built = g.filesize(hash_scratch)
        cap = (hp["_end_mib"] - hp["_start_mib"]) * 1024 * 1024
        if built > cap:
            raise RuntimeError(
                "built verity hash tree for '%s' is %d bytes, larger than "
                "its %d-byte partition '%s'"
                % (m["label"], built, cap, hp["label"]))
        g.copy_file_to_device(
            hash_scratch, DEVICE, destoffset=hp["_start_mib"] * 1024 * 1024)
        g.rm(hash_scratch)
        return roothash

    # gpt-auto-generator refuses an unanchored verity pair, so 'usrhash='
    # must be added for '/usr' to mount. Signed only if 'image: secure-boot:'
    # is set. Runs while 'm' and siblings are still mounted.
    def _anchor_uki(self, g, mounts, mounted, m, roothash):
        if m["_prefix"] != "/usr/":
            return
        efi_dirs = []
        for other in mounts:
            if id(other) not in mounted:
                continue
            efi_dir = "%s/EFI/Linux" % other["_prefix"].rstrip("/")
            if g.is_dir(efi_dir):
                efi_dirs.append(efi_dir)

        for efi_dir in efi_dirs:
            for name in sorted(g.ls(efi_dir)):
                if name.endswith(".efi"):
                    self._anchor_one_uki(g, efi_dir, name, roothash)

    # objcopy/ukify/sbsign run as container commands, not inside the
    # appliance, on a copy of the '.efi' downloaded to a scratch dir.
    def _anchor_one_uki(self, g, efi_dir, name, roothash):
        print("Anchoring '%s' with usrhash=%s..." % (name, roothash))
        efi_path = "%s/%s" % (efi_dir, name)
        workdir = tempfile.mkdtemp(dir=self._output_dir, prefix="uki-anchor-")
        original = os.path.join(workdir, "original.efi")
        g.download(efi_path, original)

        def run(args):
            ContainerEngine.run(
                ["container", "run", "--rm", "-v", "%s:/work" % workdir,
                 "-w", "/work", self._extra_tools.name] + args, check=True)

        # One objcopy dumps all three sections byte-identical to build time.
        # '/dev/null' as output makes objcopy exit 1 despite success, so use
        # a throwaway file instead.
        run(["objcopy",
             "--dump-section", ".linux=linux.bin",
             "--dump-section", ".initrd=initrd.bin",
             "--dump-section", ".cmdline=cmdline.txt",
             "original.efi", "discard.efi"])

        base_cmdline = open(os.path.join(workdir, "cmdline.txt")).read().strip()
        cmdline = ("%s usrhash=%s" % (base_cmdline, roothash)) if base_cmdline \
            else "usrhash=%s" % roothash

        # A real 'ukify build', not an 'objcopy --update-section' patch, so
        # a future PCR-policy pass only extends 'extra' here instead of a
        # second code path.
        run(ukify_argv("linux.bin", "initrd.bin", cmdline, "rebuilt.efi"))

        secure_boot = self.source.partitionHandler.secure_boot
        result = "rebuilt.efi"
        if secure_boot is not None:
            ContainerEngine.run(
                ["container", "run", "--rm", "-v", "%s:/work" % workdir,
                 "-v", "%s:/work-key:ro" % os.path.abspath(secure_boot["private-key"]),
                 "-v", "%s:/work-cert:ro" % os.path.abspath(secure_boot["public-cert"]),
                 "-w", "/work", self._extra_tools.name,
                 "sbsign", "--key", "/work-key", "--cert", "/work-cert",
                 "--output", "signed.efi", "rebuilt.efi"], check=True)
            result = "signed.efi"

        g.upload(os.path.join(workdir, result), efi_path)

    # Deepest mount first, so a mount's children are already unmounted
    # (empty dir, not live content) when read. 'mounts' is one group's
    # list -- create() handles groups one at a time.
    def _build_ro_images(self, g, mounts, mount_devices, part_index, hash_part_for):
        built_sizes = {}
        ro_mounts = [m for m in mounts if m["type"] in RO_FSTYPES]
        if not ro_mounts:
            return built_sizes

        mounted = {id(m) for m in mounts}
        tools_dir = "/.imager-extra-tools"
        g.mkdir_p(tools_dir)
        for host_path in self._extra_tools_files:
            remote_path = "%s/%s" % (tools_dir, os.path.basename(host_path))
            g.upload(host_path, remote_path)
            g.chmod(0o755, remote_path)

        for m in sorted(ro_mounts, key=lambda m: m["_depth"], reverse=True):
            print("Building %s image for '%s'..." % (m["type"], m["label"]))
            for child in mounts:
                if child is not m and id(child) in mounted \
                   and child["_prefix"].startswith(m["_prefix"]):
                    g.umount(child["_prefix"])
                    mounted.discard(id(child))

            tool = "%s/%s" % (tools_dir,
                "mksquashfs" if m["type"] == "squashfs" else "mkfs.erofs")
            run = "LD_LIBRARY_PATH=%s %s" % (tools_dir, tool)

            scratch = "/%s.img" % m["label"]
            comp = m.get("compression")
            # Fixed timestamp, not real mtimes: same content must give the
            # same bytes (and verity hash) across rebuilds.
            if m["type"] == "squashfs":
                g.sh("%s %s %s -noappend -all-time %d%s" % (
                    run, m["_prefix"], scratch, FALLBACK_EPOCH,
                    " -comp %s" % comp if comp else ""))
            else:
                # mkfs.erofs takes output before source, the reverse of mksquashfs
                g.sh("%s%s -T%d %s %s" % (
                    run, " -z%s" % comp if comp else "", FALLBACK_EPOCH,
                    scratch, m["_prefix"]))

            built = g.filesize(scratch)
            built_sizes[id(m)] = built

            # Still while 'm' is mounted: g.sh() chroots via '/bin/sh' at
            # '/', a symlink into '/usr' on usrmerged targets -- unmount
            # first and g.sh() has nothing to run.
            hp = hash_part_for.get(m["label"])
            if hp is not None:
                roothash = self._build_verity(g, tools_dir, m, scratch, hp, part_index)
                self._anchor_uki(g, mounts, mounted, m, roothash)

            g.umount(m["_prefix"])
            mounted.discard(id(m))

            if m["_lvm"]:
                dest, offset, cap = mount_devices[id(m)], 0, m["size"]
            else:
                dest, offset = DEVICE, m["_start_mib"] * 1024 * 1024
                cap = (m["_end_mib"] - m["_start_mib"]) * 1024 * 1024
            if built > cap:
                raise RuntimeError(
                    "built %s image for '%s' is %d bytes, larger than its "
                    "%d-byte partition/volume" % (m["type"], m["label"], built, cap))

            g.copy_file_to_device(scratch, dest, destoffset=offset)
            g.rm(scratch)

        g.rm_rf(tools_dir)
        return built_sizes

    def _hypervisor(self, target_arch):
        imager_spec = self.source.spec.get("imager") or {}
        return imager_spec.get("hypervisor") or DEFAULT_HYPERVISORS.get(target_arch)

    # Writes a qemu wrapper fixing libguestfs's hardcoded x86 flags for
    # 'target_arch', and returns its path for g.set_hv().
    def _write_qemu_wrapper(self, output_dir, target_arch, real_hv):
        fixups = CROSS_ARCH_QEMU_FIXUPS.get(target_arch)
        if fixups is None:
            raise NotImplementedError(
                "cross-building for architecture '%s' is not yet supported "
                "(no verified qemu launch fixups)" % target_arch)
        wrapper_path = os.path.join(output_dir, "qemu-wrapper.sh")
        with open(wrapper_path, "w") as f:
            f.write(QEMU_WRAPPER_SCRIPT.format(real_hv=real_hv, **fixups))
        os.chmod(wrapper_path, os.stat(wrapper_path).st_mode | stat.S_IEXEC)
        return wrapper_path

    # Returns the hypervisor path for g.set_hv(), if any. Same-arch builds
    # use libguestfs's normal supermin auto-build. Cross-arch builds use a
    # pre-built appliance (supermin can't cross-build) plus a qemu wrapper
    # for its hardcoded x86 flags.
    def _prepare_appliance(self, output_dir):
        target_arch = self.source.spec["distribution"]["architecture"]
        if target_arch == HOST_ARCH:
            print("Preparing imager kernel...")
            imagerKernel = ImagerKernel(self.source)
            imagerKernel.create()
            vmlinuz, modules, version = imagerKernel.extract(output_dir)
            os.environ["SUPERMIN_KERNEL"] = vmlinuz
            os.environ["SUPERMIN_KERNEL_VERSION"] = version
            os.environ["SUPERMIN_MODULES"] = modules
            if self.verbose:
                print("  package: %s" % imagerKernel.package)
                print("  version: %s" % version)
            return self._hypervisor(target_arch)

        print("Preparing imager kernel...")
        imagerKernel = ImagerKernel(self.source)
        imagerKernel.create()

        print("Preparing cross-arch imager appliance for '%s'..." % target_arch)
        imagerAppliance = ImagerAppliance(self.source, imagerKernel)
        imagerAppliance.create()
        appliance_dir = imagerAppliance.extract(output_dir)
        os.environ["LIBGUESTFS_PATH"] = appliance_dir
        os.environ["LIBGUESTFS_BACKEND_SETTINGS"] = "force_tcg"

        real_hv = self._hypervisor(target_arch)
        return self._write_qemu_wrapper(output_dir, target_arch, real_hv)

    # Two separate tasks: the appliance only needs packages (for its own
    # kernel) and the target bootstrap, not the built root file-system --
    # combining them would wait on the disk unnecessarily.
    def tasks(self, needs_packages="packages"):
        return [
            Task("appliance", self._prepare,
                 needs=["bootstrap-target", needs_packages]),
            Task("image", self._build, needs=["disk", "appliance"]),
        ]

    def _prepare(self):
        # Scratch dir for the unpacked appliance kernel/modules, not kept.
        self._output_dir = tempfile.mkdtemp(dir=ContainerEngine.scratch(),
                                           prefix="imager-")
        self._hypervisor_path = self._prepare_appliance(self._output_dir)
        self._extra_tools_files = self._prepare_extra_tools(self._output_dir)

    def _prepare_extra_tools(self, output_dir):
        mounts = self.source.partitionHandler.mounts
        if not any(m["type"] in RO_FSTYPES for m in mounts):
            self._extra_tools = None
            return []
        print("Preparing read-only file-system tools...")
        need_verity = any(m.get("verity") for m in mounts)
        tools = ExtraImagerTools(self.source, need_verity=need_verity)
        tools.create()
        # Kept beyond this method: _build_ro_images()'s UKI step runs
        # objcopy/ukify/sbsign against this built image (tools.name).
        self._extra_tools = tools
        return tools.extract(output_dir)

    def _build(self):
        self.create()
        os.rename(self.source._image, self.source._output)

    def create(self):
        ph = self.source.partitionHandler
        disk = self.source._image
        output_dir = self._output_dir
        try:
            hypervisor = self._hypervisor_path

            print("Starting imager appliance...")
            g = guestfs.GuestFS(python_return_dict=True)
            g.add_drive_opts(disk, format="raw", readonly=False)
            if hypervisor:
                if self.verbose:
                    print("  hypervisor: %s" % hypervisor)
                g.set_hv(hypervisor)
            # Wraps the whole session, not just g.launch(): libguestfs forks
            # again on g.shutdown()/g.close(), which hangs if left unguarded.
            before_launch()
            try:
                g.launch()

                part_devices, part_index, hash_part_for = self._create_partitions(g, ph)
                vol_devices = self._create_volumes(g, ph, part_devices)

                # Grouped by 'source': 'None' is a spec with no 'multiconfig:'
                # groups. Declared groups are side-by-side, non-overlapping
                # OSes, mounted and unmounted one at a time.
                by_source = {}
                for m in ph.mounts:
                    by_source.setdefault(m.get("source"), []).append(m)
                declared_groups = sorted(name for name in by_source if name is not None)
                sources = ([None] if None in by_source else []) + declared_groups

                # Boot owner goes last: its iteration writes every group's
                # grub.cfg entry, so all other kernels/initrds must be known first.
                boot_owner = (self.source.spec.get("imager") or {}).get("boot") or "main"
                if declared_groups:
                    if boot_owner not in declared_groups:
                        raise RuntimeError(
                            "'imager: boot: %s' is not one of the declared "
                            "'multiconfig:' groups (%s)"
                            % (boot_owner, ", ".join(declared_groups)))
                    sources = [s for s in sources if s != boot_owner] + [boot_owner]

                boot_entries = []
                for source in sources:
                    mounts = sorted(by_source[source], key=lambda m: m["_depth"])
                    mount_devices = self._populate_source(
                        g, ph, source, mounts, part_devices, vol_devices, part_index)
                    self._install_boot_entry(
                        g, part_index, source, mounts, boot_owner, boot_entries)
                    built_sizes = self._build_ro_images(
                        g, mounts, mount_devices, part_index, hash_part_for)
                    self._print_disk_usage(g, ph, mounts, built_sizes)
                    g.umount_all()

                g.shutdown()
                g.close()
                print("Done.")
            finally:
                after_launch()
        finally:
            if self.keep:
                print("keeping '%s' (imager kernel files) as requested" % output_dir)
            else:
                shutil.rmtree(output_dir, ignore_errors=True)

    def _create_partitions(self, g, ph):
        print("Partitioning (%s)..." % ph._table)
        g.part_init(DEVICE, ph._table)
        target_arch = self.source.spec["distribution"]["architecture"]
        partitions_by_label = {p["label"]: p for p in ph.partitions}
        hash_part_for = {p["verity-for"]: p for p in ph.partitions
                         if p["type"] == VERITY_HASH_TYPE}
        part_devices = {}
        part_index = {}
        index = 1
        for part in ph.partitions:
            dev = self._partition_device(
                g, ph._table, part, index, target_arch, partitions_by_label)
            part_devices[id(part)] = dev
            part_index[id(part)] = index
            if part["_lvm"]:
                g.pvcreate(dev)
            elif part["type"] != VERITY_HASH_TYPE:
                self._mkfs(g, part, dev)
            index = index + 1
        return part_devices, part_index, hash_part_for

    def _create_volumes(self, g, ph, part_devices):
        for group in ph.groups:
            pvs = [part_devices[id(p)] for p in ph.partitions
                   if p["_lvm"] and p.get("group") == group]
            if not pvs:
                raise RuntimeError("no physical volume found for LVM group '%s'!" % group)
            g.vgcreate(group, pvs)

        vol_devices = {}
        for vol in ph.volumes:
            g.lvcreate(vol["label"], vol["group"], ph._to_rounded_mib(vol["size"]))
            voldev = "/dev/%s/%s" % (vol["group"], vol["label"])
            self._mkfs(g, vol, voldev)
            vol_devices[id(vol)] = voldev
        return vol_devices

    def _populate_source(self, g, ph, source, mounts, part_devices, vol_devices, part_index):
        print("Mounting %s file-systems..."
              % (("'%s'" % source) if source else "the image's own"))
        mount_devices = {}
        for m in mounts:
            dev = part_devices.get(id(m)) or vol_devices.get(id(m))
            mount_devices[id(m)] = dev
            if m["_prefix"] != "/":
                prefix = m["_prefix"].rstrip("/")
                parent = os.path.dirname(prefix)
                if parent and parent != "/":
                    g.mkdir_p(parent)
                g.mkmountpoint(prefix)
            g.mount(dev, m["_prefix"])

        print("Extracting root file-system...")
        tarball = self.source._tarball_for(source)
        g.tar_in(tarball, "/")

        print("Restoring extended attributes...")
        self._restore_xattrs(g, tarball)

        print("Writing fstab...")
        self._write_fstab(g, mounts, mount_devices, part_index)

        if source is None:
            print("Copying bootlets...")
            for bootlet in ph.bootlets:
                data = g.read_file(bootlet["file"])
                g.pwrite_device(DEVICE, data, bootlet["_seek"] * 1024)

        self._label_selinux(g, mounts)
        return mount_devices

    def _install_boot_entry(self, g, part_index, source, mounts, boot_owner, boot_entries):
        # source is None: plain single update-grub call. A declared group
        # instead records its boot info; the boot owner (last) writes every
        # group's menuentry, itself first as the static default.
        root_m = next((m for m in mounts if m["_prefix"] == "/"), None)
        if root_m is not None and source is None:
            bootloader = detect_bootloader(g, DEVICE)
            if bootloader:
                print("Installing grub...")
                bootloader.install(g, "/efi")
                bootloader.add_entry(g)
        elif root_m is not None:
            boot_files = self._boot_files(g)
            if boot_files is not None:
                if id(root_m) not in part_index:
                    raise RuntimeError(
                        "'multiconfig:' group '%s' has an LVM root -- "
                        "a per-group GRUB boot entry needs a GPT "
                        "partition, not a logical volume" % source)
                kernel, initrd = boot_files
                boot_entries.append({
                    "label": source,
                    "kernel": kernel,
                    "initrd": initrd,
                    "root_partuuid": self._partuuid(g, part_index, root_m),
                    "root_label": root_m["label"],
                    "cmdline": self._grub_cmdline(g),
                })
            if source == boot_owner:
                bootloader = detect_bootloader(g, DEVICE)
                if bootloader:
                    print("Installing grub...")
                    bootloader.install(g, "/efi", boot_directory="/efi")
                    ordered = [e for e in boot_entries if e["label"] == boot_owner] + \
                        [e for e in boot_entries if e["label"] != boot_owner]
                    for entry in ordered:
                        bootloader.add_entry(
                            g, group_label=entry["label"],
                            kernel=entry["kernel"], initrd=entry["initrd"],
                            root_partuuid=entry["root_partuuid"],
                            root_label=entry["root_label"],
                            cmdline=entry["cmdline"])

    def _print_disk_usage(self, g, ph, mounts, built_sizes):
        print("Disk usage:")
        for m in mounts:
            if m["type"] in RO_FSTYPES:
                print("%s\t%s (%s)" % (
                    m["_prefix"], ph._to_human_size(built_sizes[id(m)]), m["type"]))
                continue
            st = g.statvfs(m["_prefix"])
            total = st["blocks"] * st["frsize"]
            used = total - st["bfree"] * st["frsize"]
            print("%s\t%s used / %s total" % (
                m["_prefix"], ph._to_human_size(used), ph._to_human_size(total)))
