# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0

import os
import re
import shutil
import stat
import tarfile
import tempfile

import guestfs

from seine.bootloader        import detect as detect_bootloader
from seine.imager_appliance import ImagerAppliance
from seine.imager_kernel    import ImagerKernel
from seine.imager_extra_tools import ExtraImagerTools
from seine.packages          import FALLBACK_EPOCH
from seine.partition        import RO_FSTYPES
from seine.tasks import Task
from seine.utils            import ContainerEngine
from seine.utils            import HOST_ARCH

DEVICE = "/dev/sda"

# Neither squashfs nor erofs is a g.mkfs() target -- RO_FSTYPES mounts are
# staged as this, then replaced with the real built image (see the finalize
# pass in create()).
STAGING_TYPE = "ext4"

# GPT partition type GUIDs.
GPT_TYPE_ESP = "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
GPT_TYPE_LVM = "E6D6D379-F507-44C2-A23C-238F2A3DF928"
GPT_TYPE_XBOOTLDR = "BC13C2FF-59E6-4262-A352-B275FD6F7172"

# Discoverable Partition Specification: root and '/usr' are architecture-
# specific (a mixed-architecture disk must not have either auto-discovered
# under the wrong kernel); '/var', '/var/tmp', '/home' and '/srv' are
# universal. Keyed by seine's own 'distribution: architecture:' names, same
# as DEFAULT_HYPERVISORS above.
GPT_TYPE_ROOT = {
    "amd64": "4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709",
    "arm64": "B921B045-1DF0-41C3-AF44-4C6F280D3FAE",
    "armhf": "69DAD710-2CE4-4E3C-B16C-21A1D49ABED3",
    "i386":  "44479540-F297-41B2-9AF7-D131D5F0458A",
}
GPT_TYPE_USR = {
    "amd64": "8484680C-9521-48C6-9C11-B0720656F69E",
    "arm64": "B0E01050-EE5F-4390-949A-9101B17104E9",
    "armhf": "7D0359A3-02B3-4F0A-865C-654403E70625",
    "i386":  "75250D76-8CC6-458E-BD66-BD47CC81A812",
}
GPT_TYPE_VAR = "4D21B016-B534-45C2-A9FB-5C16E091FD2D"
GPT_TYPE_VAR_TMP = "7EC6F557-3BC5-4ACA-B293-16EF5DF639D1"
GPT_TYPE_HOME = "933AC7E1-2EB4-4F13-B844-0E14E2AEF915"
GPT_TYPE_SRV = "3B8F8425-20E0-4F3B-907F-1A25A76F98E8"

# Fallback hypervisor per architecture, used to boot a genuine target-arch
# appliance when cross-building and 'imager: hypervisor:' is not set in the
# specification (e.g. building an arm64 image on an amd64 host: the imager
# appliance's own kernel is already arm64 via ImagerKernel/TargetBootstrap,
# but guestfs still needs to be told to launch qemu-system-aarch64 instead
# of its host-arch default).
DEFAULT_HYPERVISORS = {
    "amd64": "/usr/bin/qemu-system-x86_64",
    "arm64": "/usr/bin/qemu-system-aarch64",
    "armhf": "/usr/bin/qemu-system-arm",
    "i386":  "/usr/bin/qemu-system-i386",
}

# libguestfs's launch-command construction hardcodes several x86-only
# assumptions (machine type, CPU properties, serial console name) for *any*
# hypervisor binary, with no override mechanism exposed for some of them
# (e.g. -global virtio-blk-pci.scsi=off has no "last flag wins" escape the
# way -machine/-cpu do). Confirmed only for arm64 so far -- verified via a
# real cross-arch build, not guessed.
CROSS_ARCH_QEMU_FIXUPS = {
    "arm64": {"machine": "virt,accel=tcg", "cpu": "max", "console": "ttyAMA0"},
}

QEMU_WRAPPER_SCRIPT = """#!/bin/bash
# generated by seine -- rewrites qemu flags that libguestfs hardcodes
# unconditionally but that don't apply on this (non-x86) target, then
# execs the real hypervisor.
args=()
while [ $# -gt 0 ]; do
    case "$1" in
        -global)
            if [ "$2" = "virtio-blk-pci.scsi=off" ]; then
                shift 2
                continue
            fi
            ;;
        -machine)
            args+=("-machine" "{machine}")
            shift 2
            continue
            ;;
        -cpu)
            args+=("-cpu" "{cpu}")
            shift 2
            continue
            ;;
        -append)
            args+=("-append" "${{2/console=ttyS0/console={console}}}")
            shift 2
            continue
            ;;
    esac
    args+=("$1")
    shift
done
exec "{real_hv}" "${{args[@]}}"
"""

# Hooks around the one g.launch() call below, a no-op pair CLI builds
# never touch. libguestfs's C library forks+execs its qemu appliance
# there, a real fork() this module has no control over -- when the TUI
# has a live '/target' (mtda) connection, seine/tui/target.py's own
# _wire_launch_guard() points these at disconnecting/reconnecting it,
# since that channel's background threads are exactly what stalls a
# real fork() forever (see that module's comment for the fork_support/
# thread_pool detail).
before_launch = lambda: None
after_launch = lambda: None

class Imager:
    def __init__(self, source):
        self.source = source
        self.keep = source.options["keep"]
        self.verbose = source.options["verbose"]

    # Filters a `getfattr -Rh -d -e hex` dump down to entries for files that
    # actually made it into the tarball (getfattr walked the target
    # container's live filesystem, which includes things -- like the
    # python3/python3-apt/attr transport packages themselves -- that were
    # later removed before the tarball was exported).
    def _filter_xattr_dump(self, text, known_files):
        blocks = []
        current = []
        keep = False
        for line in text.splitlines():
            if line.startswith("# file: "):
                if keep and current:
                    blocks.append("\n".join(current))
                current = [line]
                keep = line[len("# file: "):] in known_files
            elif keep:
                current.append(line)
        if keep and current:
            blocks.append("\n".join(current))
        return "\n\n".join(blocks) + "\n"

    def _restore_xattrs(self, g, tarball):
        with tarfile.open(tarball) as tar:
            known_files = set()
            xattr_member = None
            for member in tar.getmembers():
                if member.name == "rootfs.xattr":
                    xattr_member = member
                    continue
                if member.issym() or member.isdir():
                    continue
                known_files.add(member.name)
            if xattr_member is None:
                return
            dump = tar.extractfile(xattr_member).read().decode()

        if not g.is_file("/usr/bin/setfattr"):
            print("  note: 'attr' is not installed in the target image, "
                  "skipping restore of extended attributes (e.g. file capabilities)")
            return

        # Extended attribute values (e.g. security.capability) are arbitrary
        # bytes and may contain embedded NULs, which the setxattr API calls
        # can't carry as Python str -- go through setfattr --restore instead,
        # using the target's own binary against a file we upload, since a
        # file transfer is NUL-safe where a str argument isn't.
        filtered = self._filter_xattr_dump(dump, known_files)
        g.write("/rootfs.xattr", filtered.encode())
        g.sh("setfattr --restore=/rootfs.xattr")
        g.rm("/rootfs.xattr")

    def _mkfs(self, g, part, dev):
        fstype = STAGING_TYPE if part["type"] in RO_FSTYPES else part["type"]
        g.mkfs(fstype, dev)
        if "label" in part:
            g.set_label(dev, part["label"])

    # DPS role GUID for a plain (non-ESP/LVM/XBOOTLDR) mounted partition --
    # 'None' for a mountpoint DPS gives no role to (left at parted's own
    # default, the generic Linux-filesystem-data GUID).
    DPS_UNIVERSAL_ROLES = {
        "/var/":      GPT_TYPE_VAR,
        "/var/tmp/":  GPT_TYPE_VAR_TMP,
        "/home/":     GPT_TYPE_HOME,
        "/srv/":      GPT_TYPE_SRV,
    }

    def _dps_gpt_type(self, part, target_arch):
        prefix = part.get("_prefix")
        if prefix == "/":
            return GPT_TYPE_ROOT.get(target_arch)
        if prefix == "/usr/":
            return GPT_TYPE_USR.get(target_arch)
        return self.DPS_UNIVERSAL_ROLES.get(prefix)

    def _partition_device(self, g, table, part, index, target_arch):
        start_sect = part["_start_mib"] * 2048
        end_sect = part["_end_mib"] * 2048 - 1
        flags = part.get("flags", [])
        prlogex = "primary"
        if table == "msdos":
            if "extended" in flags:
                prlogex = "extended"
            if "logical" in flags:
                prlogex = "logical"
        g.part_add(DEVICE, prlogex, start_sect, end_sect)
        if table == "gpt":
            g.part_set_name(DEVICE, index, part["label"])
            if "boot" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_ESP)
            elif "lvm" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_LVM)
            elif "xbootldr" in flags:
                g.part_set_gpt_type(DEVICE, index, GPT_TYPE_XBOOTLDR)
            else:
                dps_type = self._dps_gpt_type(part, target_arch)
                if dps_type is not None:
                    g.part_set_gpt_type(DEVICE, index, dps_type)
        elif "boot" in flags:
            g.part_set_bootable(DEVICE, index, True)
        return DEVICE + str(index)

    # 'm' must be a physical partition (its id in 'part_index') -- LVM
    # volumes have no GPT partition table entry to read a PARTUUID from.
    # Lower-cased: udev's by-partuuid symlinks are, and the target's own
    # boot-time root wait matches by exact path.
    def _partuuid(self, g, part_index, m):
        return g.part_get_gpt_guid(DEVICE, part_index[id(m)]).lower()

    def _write_fstab(self, g, mount_order, mount_devices, part_index):
        fstab = []
        for m in mount_order:
            dev = mount_devices[id(m)]
            ro = m["type"] in RO_FSTYPES
            if m["_lvm"]:
                what = dev
            elif ro and m.get("identify") == "partuuid":
                what = "PARTUUID=%s" % self._partuuid(g, part_index, m)
            elif ro:
                what = "PARTLABEL=%s" % m["label"]
            else:
                what = "UUID=%s" % g.vfs_uuid(dev)
            options = "defaults"
            passno = 2
            if ro:
                options = "ro"
                passno = 0
            elif m["_prefix"] == "/":
                if m["type"] != "btrfs":
                    options = "errors=remount-ro"
                passno = 1
            elif m["type"] == "vfat":
                options = "umask=0077"
            fstab.append("%s %s %s %s 0 %d" % (what, m["_prefix"], m["type"], options, passno))
        g.write("/etc/fstab", ("\n".join(fstab) + "\n").encode())

    def _label_selinux(self, g, mount_order):
        se_contexts = "/etc/selinux/default/contexts/files/file_contexts"
        if not (g.is_file(se_contexts) and g.is_file("/usr/sbin/setfiles")):
            return
        print("Setting file contexts for SELinux...")
        if g.is_file("/etc/default/grub"):
            grub_cfg = g.read_file("/etc/default/grub").decode()
            grub_cfg = re.sub(r'^(GRUB_CMDLINE_LINUX=.*)"$', r'\1 security=selinux"',
                               grub_cfg, flags=re.MULTILINE)
            g.write("/etc/default/grub", grub_cfg.encode())
        # setfiles never crosses a filesystem boundary, so one call on "/"
        # misses every separate mount. FAT has no xattr support, so skip it
        # rather than fail on it.
        for m in mount_order:
            if m["type"] in ("vfat", "msdos", "fat", "fat32"):
                continue
            g.sh("setfiles -m%s %s %s" % (
                " -v" if self.verbose else "", se_contexts, m["_prefix"]))

    # 'None' means no kernel at all -- not every 'multiconfig:' group need
    # be bootable. Once a group does carry one, more than one kernel or
    # initrd is a build-time error, not a silent pick.
    def _boot_files(self, g):
        entries = g.ls("/boot") if g.is_dir("/boot") else []
        kernels = sorted(e for e in entries if e.startswith("vmlinuz-"))
        initrds = sorted(e for e in entries if e.startswith("initrd.img-"))
        if not kernels and not initrds:
            return None
        if len(kernels) != 1 or len(initrds) != 1:
            raise RuntimeError(
                "expected exactly one kernel and one initrd under '/boot', "
                "found %d kernel(s) and %d initrd(s) (%s)"
                % (len(kernels), len(initrds), ", ".join(entries)))
        return "/boot/%s" % kernels[0], "/boot/%s" % initrds[0]

    # What 'update-grub' itself would fold into a normal entry's own
    # 'linux' line -- read here since a per-group entry is authored
    # directly rather than generated by 'update-grub' (which reads this
    # file itself for the single-rootfs case).
    def _grub_cmdline(self, g):
        if not g.is_file("/etc/default/grub"):
            return ""
        conf = g.read_file("/etc/default/grub").decode()
        parts = []
        for name in ("GRUB_CMDLINE_LINUX_DEFAULT", "GRUB_CMDLINE_LINUX"):
            m = re.search(r'^%s="(.*)"' % name, conf, re.MULTILINE)
            if m and m.group(1).strip():
                parts.append(m.group(1).strip())
        return " ".join(parts)

    # Deepest mount first, so a packed mount's own children are already
    # unmounted (an empty dir, not live content) by the time it's read.
    # 'mounts' is one group's own currently-mounted list (create() mounts
    # one group at a time), not every mount on the disk -- unmounting a
    # sibling group's own child here would reach for a path nothing has
    # mounted yet.
    def _build_ro_images(self, g, mounts, mount_devices):
        built_sizes = {}
        ro_mounts = [m for m in mounts if m["type"] in RO_FSTYPES]
        if not ro_mounts:
            return built_sizes

        mounted = {id(m) for m in mounts}
        tools_dir = "/.imager-extra-tools"
        g.mkdir_p(tools_dir)
        for host_path in self._extra_tools_files:
            remote_path = "%s/%s" % (tools_dir, os.path.basename(host_path))
            g.upload(host_path, remote_path)
            g.chmod(0o755, remote_path)

        for m in sorted(ro_mounts, key=lambda m: m["_depth"], reverse=True):
            print("Building %s image for '%s'..." % (m["type"], m["label"]))
            for child in mounts:
                if child is not m and id(child) in mounted \
                   and child["_prefix"].startswith(m["_prefix"]):
                    g.umount(child["_prefix"])
                    mounted.discard(id(child))

            tool = "%s/%s" % (tools_dir,
                "mksquashfs" if m["type"] == "squashfs" else "mkfs.erofs")
            run = "LD_LIBRARY_PATH=%s %s" % (tools_dir, tool)

            scratch = "/%s.img" % m["label"]
            comp = m.get("compression")
            # Fixed timestamp, not real mtimes: identical content must give
            # identical bytes (and so the same verity root hash) across
            # rebuilds. Same fallback value packages.py uses when a tree
            # has no other date to go by.
            if m["type"] == "squashfs":
                g.sh("%s %s %s -noappend -all-time %d%s" % (
                    run, m["_prefix"], scratch, FALLBACK_EPOCH,
                    " -comp %s" % comp if comp else ""))
            else:
                # mkfs.erofs takes output before source, the reverse of mksquashfs
                g.sh("%s%s -T%d %s %s" % (
                    run, " -z%s" % comp if comp else "", FALLBACK_EPOCH,
                    scratch, m["_prefix"]))

            built = g.filesize(scratch)
            built_sizes[id(m)] = built
            g.umount(m["_prefix"])
            mounted.discard(id(m))

            if m["_lvm"]:
                dest, offset, cap = mount_devices[id(m)], 0, m["size"]
            else:
                dest, offset = DEVICE, m["_start_mib"] * 1024 * 1024
                cap = (m["_end_mib"] - m["_start_mib"]) * 1024 * 1024
            if built > cap:
                raise RuntimeError(
                    "built %s image for '%s' is %d bytes, larger than its "
                    "%d-byte partition/volume" % (m["type"], m["label"], built, cap))

            g.copy_file_to_device(scratch, dest, destoffset=offset)
            g.rm(scratch)

        g.rm_rf(tools_dir)
        return built_sizes

    def _hypervisor(self, target_arch):
        imager_spec = self.source.spec.get("imager") or {}
        return imager_spec.get("hypervisor") or DEFAULT_HYPERVISORS.get(target_arch)

    # Writes a qemu wrapper script that fixes up the hardcoded x86 flags in
    # libguestfs's launch command for the given target architecture, and
    # returns its path (for use with g.set_hv()).
    def _write_qemu_wrapper(self, output_dir, target_arch, real_hv):
        fixups = CROSS_ARCH_QEMU_FIXUPS.get(target_arch)
        if fixups is None:
            raise NotImplementedError(
                "cross-building for architecture '%s' is not yet supported "
                "(no verified qemu launch fixups)" % target_arch)
        wrapper_path = os.path.join(output_dir, "qemu-wrapper.sh")
        with open(wrapper_path, "w") as f:
            f.write(QEMU_WRAPPER_SCRIPT.format(real_hv=real_hv, **fixups))
        os.chmod(wrapper_path, os.stat(wrapper_path).st_mode | stat.S_IEXEC)
        return wrapper_path

    # Prepares the imager appliance and returns the hypervisor path (if any)
    # to pass to g.set_hv(). Same-arch builds use libguestfs's normal
    # supermin auto-build (via ImagerKernel/SUPERMIN_KERNEL, sidestepping
    # only the host /boot-permission problem). Cross-arch builds use a
    # pre-built "fixed appliance" (ImagerAppliance/LIBGUESTFS_PATH), since
    # supermin cannot cross-build, plus a qemu wrapper script, since
    # libguestfs's launch command hardcodes several x86-only assumptions
    # regardless of hypervisor.
    def _prepare_appliance(self, output_dir):
        target_arch = self.source.spec["distribution"]["architecture"]
        if target_arch == HOST_ARCH:
            print("Preparing imager kernel...")
            imagerKernel = ImagerKernel(self.source)
            imagerKernel.create()
            vmlinuz, modules, version = imagerKernel.extract(output_dir)
            os.environ["SUPERMIN_KERNEL"] = vmlinuz
            os.environ["SUPERMIN_KERNEL_VERSION"] = version
            os.environ["SUPERMIN_MODULES"] = modules
            if self.verbose:
                print("  package: %s" % imagerKernel.package)
                print("  version: %s" % version)
            return self._hypervisor(target_arch)

        print("Preparing imager kernel...")
        imagerKernel = ImagerKernel(self.source)
        imagerKernel.create()

        print("Preparing cross-arch imager appliance for '%s'..." % target_arch)
        imagerAppliance = ImagerAppliance(self.source, imagerKernel)
        imagerAppliance.create()
        appliance_dir = imagerAppliance.extract(output_dir)
        os.environ["LIBGUESTFS_PATH"] = appliance_dir
        os.environ["LIBGUESTFS_BACKEND_SETTINGS"] = "force_tcg"

        real_hv = self._hypervisor(target_arch)
        return self._write_qemu_wrapper(output_dir, target_arch, real_hv)

    # Two steps rather than one. The appliance -- seine's own kernel and
    # the guestfs tooling around it -- is made from the packages and the
    # target bootstrap, and has nothing to do with the root file-system
    # being built for the image. Kept as one step it waited for a root
    # file-system it never reads, which for an emulated architecture is
    # the longest part of the build.
    #
    # It does need the packages: its kernel is installed from the
    # repository they land in, which is what makes it boot the kernel the
    # specification rebuilt rather than the distribution's. 'needs_packages'
    # is the barrier's name, same as own_tasks()'s own -- see there for who
    # asks for something other than plain 'packages'.
    def tasks(self, needs_packages="packages"):
        return [
            Task("appliance", self._prepare,
                 needs=["bootstrap-target", needs_packages]),
            Task("image", self._build, needs=["disk", "appliance"]),
        ]

    def _prepare(self):
        # The appliance's kernel and modules are unpacked here, which is a
        # lot of nothing anyone asked to keep: the scratch space, not the
        # checkout.
        self._output_dir = tempfile.mkdtemp(dir=ContainerEngine.scratch(),
                                           prefix="imager-")
        self._hypervisor_path = self._prepare_appliance(self._output_dir)
        self._extra_tools_files = self._prepare_extra_tools(self._output_dir)

    def _prepare_extra_tools(self, output_dir):
        if not any(m["type"] in RO_FSTYPES for m in self.source.partitionHandler.mounts):
            return []
        print("Preparing read-only file-system tools...")
        tools = ExtraImagerTools(self.source)
        tools.create()
        return tools.extract(output_dir)

    def _build(self):
        self.create()
        os.rename(self.source._image, self.source._output)

    def create(self):
        ph = self.source.partitionHandler
        disk = self.source._image
        output_dir = self._output_dir
        try:
            hypervisor = self._hypervisor_path

            print("Starting imager appliance...")
            g = guestfs.GuestFS(python_return_dict=True)
            g.add_drive_opts(disk, format="raw", readonly=False)
            if hypervisor:
                if self.verbose:
                    print("  hypervisor: %s" % hypervisor)
                g.set_hv(hypervisor)
            # Disconnected for the whole guestfs session, not just
            # g.launch(): libguestfs's C library forks+execs again during
            # g.shutdown()/g.close() (confirmed by testing this exact
            # wrap -- a launch-only guard hung again on close()), so
            # anything narrower would just move where the hang happens.
            before_launch()
            try:
                g.launch()

                print("Partitioning (%s)..." % ph._table)
                g.part_init(DEVICE, ph._table)
                target_arch = self.source.spec["distribution"]["architecture"]
                part_devices = {}
                part_index = {}
                index = 1
                for part in ph.partitions:
                    dev = self._partition_device(g, ph._table, part, index, target_arch)
                    part_devices[id(part)] = dev
                    part_index[id(part)] = index
                    if part["_lvm"]:
                        g.pvcreate(dev)
                    else:
                        self._mkfs(g, part, dev)
                    index = index + 1

                for group in ph.groups:
                    pvs = [part_devices[id(p)] for p in ph.partitions
                           if p["_lvm"] and p.get("group") == group]
                    if not pvs:
                        raise RuntimeError("no physical volume found for LVM group '%s'!" % group)
                    g.vgcreate(group, pvs)

                vol_devices = {}
                for vol in ph.volumes:
                    g.lvcreate(vol["label"], vol["group"], ph._to_rounded_mib(vol["size"]))
                    voldev = "/dev/%s/%s" % (vol["group"], vol["label"])
                    self._mkfs(g, vol, voldev)
                    vol_devices[id(vol)] = voldev

                # Grouped by 'source': 'None' is this specification's own
                # (so a spec with no 'multiconfig:' key takes this loop
                # once, unchanged). A declared group's own mounts never
                # overlap another's in guestfs -- groups are side-by-side,
                # non-overlapping OSes, mounted and unmounted one at a
                # time instead of all at once.
                by_source = {}
                for m in ph.mounts:
                    by_source.setdefault(m.get("source"), []).append(m)
                declared_groups = sorted(name for name in by_source if name is not None)
                sources = ([None] if None in by_source else []) + declared_groups

                # Moved to the end of 'sources': the boot-owner group's own
                # iteration writes every group's grub.cfg entry, so every
                # other group's own kernel/initrd must already be known.
                boot_owner = (self.source.spec.get("imager") or {}).get("boot") or "main"
                if declared_groups:
                    if boot_owner not in declared_groups:
                        raise RuntimeError(
                            "'imager: boot: %s' is not one of the declared "
                            "'multiconfig:' groups (%s)"
                            % (boot_owner, ", ".join(declared_groups)))
                    sources = [s for s in sources if s != boot_owner] + [boot_owner]

                boot_entries = []
                for source in sources:
                    mounts = sorted(by_source[source], key=lambda m: m["_depth"])
                    print("Mounting %s file-systems..."
                          % (("'%s'" % source) if source else "the image's own"))
                    mount_devices = {}
                    for m in mounts:
                        dev = part_devices.get(id(m)) or vol_devices.get(id(m))
                        mount_devices[id(m)] = dev
                        if m["_prefix"] != "/":
                            prefix = m["_prefix"].rstrip("/")
                            parent = os.path.dirname(prefix)
                            if parent and parent != "/":
                                g.mkdir_p(parent)
                            g.mkmountpoint(prefix)
                        g.mount(dev, m["_prefix"])

                    print("Extracting root file-system...")
                    tarball = self.source._tarball_for(source)
                    g.tar_in(tarball, "/")

                    print("Restoring extended attributes...")
                    self._restore_xattrs(g, tarball)

                    print("Writing fstab...")
                    self._write_fstab(g, mounts, mount_devices, part_index)

                    if source is None:
                        print("Copying bootlets...")
                        for bootlet in ph.bootlets:
                            data = g.read_file(bootlet["file"])
                            g.pwrite_device(DEVICE, data, bootlet["_seek"] * 1024)

                    self._label_selinux(g, mounts)

                    # source is None keeps today's single update-grub call
                    # unchanged. A declared 'multiconfig:' group instead
                    # records its own boot info now; the boot-owner group
                    # (last in 'sources') writes every group's menuentry,
                    # itself first so it stays the static default.
                    root_m = next((m for m in mounts if m["_prefix"] == "/"), None)
                    if root_m is not None and source is None:
                        bootloader = detect_bootloader(g, DEVICE)
                        if bootloader:
                            print("Installing grub...")
                            bootloader.install(g, "/efi")
                            bootloader.add_entry(g)
                    elif root_m is not None:
                        boot_files = self._boot_files(g)
                        if boot_files is not None:
                            if id(root_m) not in part_index:
                                raise RuntimeError(
                                    "'multiconfig:' group '%s' has an LVM root -- "
                                    "a per-group GRUB boot entry needs a GPT "
                                    "partition, not a logical volume" % source)
                            kernel, initrd = boot_files
                            boot_entries.append({
                                "label": source,
                                "kernel": kernel,
                                "initrd": initrd,
                                "root_partuuid": self._partuuid(g, part_index, root_m),
                                "root_label": root_m["label"],
                                "cmdline": self._grub_cmdline(g),
                            })
                        if source == boot_owner:
                            bootloader = detect_bootloader(g, DEVICE)
                            if bootloader:
                                print("Installing grub...")
                                bootloader.install(g, "/efi", boot_directory="/efi")
                                ordered = [e for e in boot_entries if e["label"] == boot_owner] + \
                                    [e for e in boot_entries if e["label"] != boot_owner]
                                for entry in ordered:
                                    bootloader.add_entry(
                                        g, group_label=entry["label"],
                                        kernel=entry["kernel"], initrd=entry["initrd"],
                                        root_partuuid=entry["root_partuuid"],
                                        root_label=entry["root_label"],
                                        cmdline=entry["cmdline"])

                    built_sizes = self._build_ro_images(g, mounts, mount_devices)

                    print("Disk usage:")
                    for m in mounts:
                        if m["type"] in RO_FSTYPES:
                            print("%s\t%s (%s)" % (
                                m["_prefix"], ph._to_human_size(built_sizes[id(m)]), m["type"]))
                            continue
                        st = g.statvfs(m["_prefix"])
                        total = st["blocks"] * st["frsize"]
                        used = total - st["bfree"] * st["frsize"]
                        print("%s\t%s used / %s total" % (
                            m["_prefix"], ph._to_human_size(used), ph._to_human_size(total)))

                    g.umount_all()

                g.shutdown()
                g.close()
                print("Done.")
            finally:
                after_launch()
        finally:
            if self.keep:
                print("keeping '%s' (imager kernel files) as requested" % output_dir)
            else:
                shutil.rmtree(output_dir, ignore_errors=True)
