# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier Apache-2.0

# Scans an SBOM for known CVEs, via debsbom's own 'sec-scan' subcommand
# (the same container image seine/sbom.py generates an SBOM from) or an
# external program named by settings.sbom2cve_program.

import getopt
import json
import os
import re
import subprocess
import sys
from collections import Counter
from typing import NamedTuple

from seine.cmd import Cmd
from seine import settings
from seine.sbom import DEBSBOM_IMAGE, output_path
from seine.utils import ContainerEngine

# One finding: a single CVE against a single (source) package. 'urgency'
# is Debian's own triage label (high/medium/low/unimportant/end-of-life/
# not-yet-assigned) -- debsbom's JSON-lines output carries no CVSS or
# other numeric severity at all, verified against a real scan of
# examples/pc-image's own SBOM while this was written.
class Finding(NamedTuple):
    cve: str
    package: str
    version: str
    urgency: str
    status: str
    tracker: str

# debsbom's own '-f json' output is JSON-lines, one finding per line, not
# a single JSON document -- each line parsed on its own so one bad line
# (a truncated write, say) does not take the rest of a 1000+-line scan
# down with it.
def parse_lines(text):
    findings = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except ValueError:
            continue
        vulnerability = entry.get("vulnerability")
        if not isinstance(vulnerability, dict) or not vulnerability.get("id"):
            continue
        package, _, version = entry.get("package", "").partition("@")
        if not package:
            continue
        findings.append(Finding(
            cve=vulnerability["id"],
            package=package,
            version=version,
            urgency=vulnerability.get("urgency", ""),
            status=vulnerability.get("status", ""),
            tracker=vulnerability.get("tracker", "")))
    return findings

# Beside the SBOM itself, the same "next to what it describes" placement
# seine/sbom.py's own output uses.
def cache_path(sbom_path):
    return sbom_path + ".issues.json"

# A cache older than the SBOM it was scanned from is stale -- an SBOM
# regenerated by a later build (same file path, new content) must not
# read back a scan of what used to be there. Anything else wrong with
# the cache (missing, unreadable, not what json.load() expects) is
# treated the same as "no cache yet": scan() runs a fresh one rather
# than raising. Public (not '_read_cache') so a caller that must never
# trigger a real scan itself -- seine/tui/ai.py's own read-only 'issues'
# tool, a container run or an external program being too consequential
# for it to start on its own -- can read the cache without going
# through scan() at all.
def read_cache(sbom_path):
    path = cache_path(sbom_path)
    try:
        if os.path.getmtime(path) < os.path.getmtime(sbom_path):
            return None
    except OSError:
        return None
    try:
        with open(path) as f:
            raw = json.load(f)
        return [Finding(**entry) for entry in raw]
    except (OSError, ValueError, TypeError):
        return None

# Written beside itself and moved into place, same as settings.save() and
# seine.cache_index.Index._write() -- a reader never sees half a write.
def _write_cache(sbom_path, findings):
    path = cache_path(sbom_path)
    temporary = "%s.new" % path
    with open(temporary, "w") as f:
        json.dump([finding._asdict() for finding in findings], f)
    os.replace(temporary, path)

# The command line for the built-in scanner: debsbom's own container
# image, given the SBOM read-only and a persistent cache dir for the
# security-tracker database it downloads with '--update-db' -- refetching
# that on every scan would make even a cached-findings re-run of 'seine
# issues' pay for a full database download first.
def _debsbom_cmd(sbom_path, distro):
    run_cmd = ["run", "--rm",
              "-v", "%s:/sbom.json:ro,z" % sbom_path,
              "-v", "%s:/root/.cache/debsbom:z" % ContainerEngine.cache("debsbom"),
              DEBSBOM_IMAGE]
    # '-t spdx' told outright: the mounted name ('/sbom.json') carries
    # none of the '.spdx.json'/'.cdx.json' filename debsbom would
    # otherwise sniff the format from, and seine/sbom.py only ever
    # writes SPDX.
    scan_cmd = ["debsbom", "sec-scan", "--update-db", "-t", "spdx", "-f", "json"]
    if distro:
        scan_cmd += ["--distro", distro]
    scan_cmd.append("/sbom.json")
    return run_cmd + scan_cmd

# Runs the scan and returns its findings, reading a still-fresh cache
# instead where 'rescan' does not force a new one. 'distro' is the
# Debian release to check against (debsbom defaults to 'trixie' on its
# own when this is None -- callers that know a build's own release
# should pass it, rather than let an unrelated default silently apply).
#
# settings.sbom2cve_program, when set, replaces the container outright:
# it is run as 'PROGRAM SBOM_PATH' and expected to write the same
# JSON-lines shape on stdout that 'debsbom sec-scan -f json' does --
# seine only ever reads that shape back, never which program produced it.
def scan(sbom_path, distro=None, rescan=False):
    # A relative path reaches podman as a named-volume request, not a
    # bind mount ('build-space/x.json' failing to match a volume-name
    # pattern is the actual error) -- resolved once here so every path
    # below (the mount, the cache file beside it) agrees on the same
    # absolute file.
    sbom_path = os.path.realpath(sbom_path)
    if not rescan:
        cached = read_cache(sbom_path)
        if cached is not None:
            return cached

    program = settings.load()["sbom2cve_program"]
    if program:
        output = subprocess.check_output([program, sbom_path])
    else:
        # Unlike ContainerEngine.workbench()/.packages()/.chroots(),
        # .cache() alone never creates the directory it names -- podman
        # refuses to bind-mount one that doesn't exist yet.
        os.makedirs(ContainerEngine.cache("debsbom"), exist_ok=True)
        output = ContainerEngine.check_output(_debsbom_cmd(sbom_path, distro))

    findings = parse_lines(output.decode("utf-8", "replace"))
    _write_cache(sbom_path, findings)
    return findings

# Aggregate counts a caller renders however it likes (a table, a bar
# chart, plain text) -- this only counts, so a display change never
# needs a matching change here. 'unique_cves' is not 'total': the same
# CVE commonly hits more than one package (a shared library, say).
def stats(findings):
    return {
        "total": len(findings),
        "unique_cves": len({finding.cve for finding in findings}),
        "packages": len({finding.package for finding in findings}),
        "by_urgency": Counter(finding.urgency for finding in findings),
        "by_status": Counter(finding.status for finding in findings),
        "by_package": Counter(finding.package for finding in findings),
    }

# debsbom's own '--min-urgency' choices, most to least severe -- the
# order 'filter_findings' below cuts against. seine's own scan() always
# runs debsbom at its most inclusive default (everything from
# 'not-yet-assigned' up), so narrowing to a stricter minimum is done
# here instead, on findings already in hand -- shared by 'seine issues'
# and, later, the TUI's own '/issues' and its AI tool, rather than
# reimplemented per caller.
URGENCY_ORDER = ["high", "medium", "low", "unimportant", "end-of-life", "not-yet-assigned"]

# 'package' narrows by name (a regex, case-insensitive); 'min_urgency'
# drops anything less severe than it, per URGENCY_ORDER above -- a
# finding whose own urgency isn't one of those (should not happen, but
# nothing here trusts debsbom's own output blindly) is dropped rather
# than guessed into a bucket.
def filter_findings(findings, package=None, min_urgency=None):
    if package:
        try:
            regex = re.compile(package, re.IGNORECASE)
        except re.error as e:
            raise ValueError("'%s' is not a usable pattern: %s" % (package, e))
        findings = [f for f in findings if regex.search(f.package)]
    if min_urgency:
        if min_urgency not in URGENCY_ORDER:
            raise ValueError("'min_urgency' must be one of %s, not '%s'" %
                             (", ".join(URGENCY_ORDER), min_urgency))
        cutoff = URGENCY_ORDER.index(min_urgency)
        findings = [f for f in findings if f.urgency in URGENCY_ORDER
                   and URGENCY_ORDER.index(f.urgency) <= cutoff]
    return findings

# 'seine issues SPEC...' scans the SBOM a prior 'seine build --sbom' of
# SPEC left behind; 'seine issues --sbom=FILE' scans FILE directly, no
# specification needed -- the same two-form split 'seine diff' already
# uses between a specification and a bare SBOM file.
class IssuesCmd(Cmd):
    NAME = "issues"
    SHORT_OPTIONS = "h"
    LONG_OPTIONS = ["help", "sbom=", "filter=", "min-urgency=", "rescan"]
    USAGE = """
Usage:
  seine issues SPEC... [--filter=PKG] [--min-urgency=LEVEL] [--rescan]
  seine issues --sbom=FILE.spdx.json [--filter=PKG] [--min-urgency=LEVEL] [--rescan]

First form: scans the SBOM a previous 'seine build --sbom' of SPEC left
behind. Second form: scans FILE directly, no specification needed.
Both check the result against debsbom's own security tracker, or a
'sbom2cve_program' from settings.json if one is configured there.

  --filter=PKG          only findings against a package matching PKG
                         (a regex, case-insensitive)
  --min-urgency=LEVEL    only findings at or above LEVEL -- one of
                         high, medium, low, unimportant, end-of-life,
                         not-yet-assigned (the default: everything)
  --rescan               ignore a cached scan and run a fresh one
"""

    def main(self, argv):
        try:
            opts, args = getopt.getopt(argv, self.SHORT_OPTIONS, self.LONG_OPTIONS)
        except getopt.GetoptError as err:
            sys.stderr.write("%s\n%s" % (err, self.USAGE))
            sys.exit(1)
        sbom_file = package = min_urgency = None
        rescan = False
        for o, a in opts:
            if o in ("-h", "--help"):
                print(self.USAGE)
                return
            elif o == "--sbom":
                sbom_file = a
            elif o == "--filter":
                package = a
            elif o == "--min-urgency":
                min_urgency = a
            elif o == "--rescan":
                rescan = True

        if sbom_file:
            if args:
                sys.stderr.write("error: --sbom does not take a specification file\n")
                sys.exit(1)
            sbom_path, distro = sbom_file, None
        else:
            if not args:
                sys.stderr.write(
                    "error: issues command expects one or more specification "
                    "files, or --sbom=FILE\n")
                sys.exit(1)
            from seine.build import BuildCmd
            build = BuildCmd()
            build.options = dict(build.options, ansible_library=[])
            try:
                build.load_all(args)
                build.parse()
            except OSError as e:
                sys.stderr.write("error: couldn't open specification file: %s\n" % e)
                sys.exit(2)
            except ValueError as e:
                sys.stderr.write("error: specification is invalid: %s\n" % e)
                sys.exit(3)
            distro = build.spec["distribution"]["release"]
            sbom_path = output_path(build.image._output)
            if not os.path.isfile(sbom_path):
                sys.stderr.write(
                    "error: no SBOM for this build yet -- run 'seine build "
                    "--sbom' first\n")
                sys.exit(4)

        try:
            findings = scan(sbom_path, distro=distro, rescan=rescan)
            findings = filter_findings(findings, package=package, min_urgency=min_urgency)
        except ValueError as e:
            sys.stderr.write("error: %s\n" % e)
            sys.exit(1)
        except (OSError, subprocess.CalledProcessError) as e:
            sys.stderr.write("error: scan failed: %s\n" % e)
            sys.exit(5)

        if not findings:
            print("no known CVEs found")
            return
        width = max(len(f.package) for f in findings)
        for f in findings:
            print("%-16s %-*s %-18s %s" % (f.cve, width, f.package, f.urgency, f.status))
