# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier Apache-2.0

# Scans an SBOM for known CVEs, via debsbom's own 'sec-scan' subcommand
# (the same container image seine/sbom.py generates an SBOM from) or an
# external program named by settings.sbom2cve_program.

import json
import os
import subprocess
from collections import Counter
from typing import NamedTuple

from seine import settings
from seine.sbom import DEBSBOM_IMAGE
from seine.utils import ContainerEngine

# One finding: a single CVE against a single (source) package. 'urgency'
# is Debian's own triage label (high/medium/low/unimportant/end-of-life/
# not-yet-assigned) -- debsbom's JSON-lines output carries no CVSS or
# other numeric severity at all, verified against a real scan of
# examples/pc-image's own SBOM while this was written.
class Finding(NamedTuple):
    cve: str
    package: str
    version: str
    urgency: str
    status: str
    tracker: str

# debsbom's own '-f json' output is JSON-lines, one finding per line, not
# a single JSON document -- each line parsed on its own so one bad line
# (a truncated write, say) does not take the rest of a 1000+-line scan
# down with it.
def parse_lines(text):
    findings = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except ValueError:
            continue
        vulnerability = entry.get("vulnerability")
        if not isinstance(vulnerability, dict) or not vulnerability.get("id"):
            continue
        package, _, version = entry.get("package", "").partition("@")
        if not package:
            continue
        findings.append(Finding(
            cve=vulnerability["id"],
            package=package,
            version=version,
            urgency=vulnerability.get("urgency", ""),
            status=vulnerability.get("status", ""),
            tracker=vulnerability.get("tracker", "")))
    return findings

# Beside the SBOM itself, the same "next to what it describes" placement
# seine/sbom.py's own output uses.
def cache_path(sbom_path):
    return sbom_path + ".issues.json"

# A cache older than the SBOM it was scanned from is stale -- an SBOM
# regenerated by a later build (same file path, new content) must not
# read back a scan of what used to be there. Anything else wrong with
# the cache (missing, unreadable, not what json.load() expects) is
# treated the same as "no cache yet": scan() runs a fresh one rather
# than raising.
def _read_cache(sbom_path):
    path = cache_path(sbom_path)
    try:
        if os.path.getmtime(path) < os.path.getmtime(sbom_path):
            return None
    except OSError:
        return None
    try:
        with open(path) as f:
            raw = json.load(f)
        return [Finding(**entry) for entry in raw]
    except (OSError, ValueError, TypeError):
        return None

# Written beside itself and moved into place, same as settings.save() and
# seine.cache_index.Index._write() -- a reader never sees half a write.
def _write_cache(sbom_path, findings):
    path = cache_path(sbom_path)
    temporary = "%s.new" % path
    with open(temporary, "w") as f:
        json.dump([finding._asdict() for finding in findings], f)
    os.replace(temporary, path)

# The command line for the built-in scanner: debsbom's own container
# image, given the SBOM read-only and a persistent cache dir for the
# security-tracker database it downloads with '--update-db' -- refetching
# that on every scan would make even a cached-findings re-run of 'seine
# issues' pay for a full database download first.
def _debsbom_cmd(sbom_path, distro):
    run_cmd = ["run", "--rm",
              "-v", "%s:/sbom.json:ro,z" % sbom_path,
              "-v", "%s:/root/.cache/debsbom:z" % ContainerEngine.cache("debsbom"),
              DEBSBOM_IMAGE]
    scan_cmd = ["debsbom", "sec-scan", "--update-db", "-f", "json"]
    if distro:
        scan_cmd += ["--distro", distro]
    scan_cmd.append("/sbom.json")
    return run_cmd + scan_cmd

# Runs the scan and returns its findings, reading a still-fresh cache
# instead where 'rescan' does not force a new one. 'distro' is the
# Debian release to check against (debsbom defaults to 'trixie' on its
# own when this is None -- callers that know a build's own release
# should pass it, rather than let an unrelated default silently apply).
#
# settings.sbom2cve_program, when set, replaces the container outright:
# it is run as 'PROGRAM SBOM_PATH' and expected to write the same
# JSON-lines shape on stdout that 'debsbom sec-scan -f json' does --
# seine only ever reads that shape back, never which program produced it.
def scan(sbom_path, distro=None, rescan=False):
    if not rescan:
        cached = _read_cache(sbom_path)
        if cached is not None:
            return cached

    program = settings.load()["sbom2cve_program"]
    if program:
        output = subprocess.check_output([program, sbom_path])
    else:
        output = ContainerEngine.check_output(_debsbom_cmd(sbom_path, distro))

    findings = parse_lines(output.decode("utf-8", "replace"))
    _write_cache(sbom_path, findings)
    return findings

# Aggregate counts a caller renders however it likes (a table, a bar
# chart, plain text) -- this only counts, so a display change never
# needs a matching change here. 'unique_cves' is not 'total': the same
# CVE commonly hits more than one package (a shared library, say).
def stats(findings):
    return {
        "total": len(findings),
        "unique_cves": len({finding.cve for finding in findings}),
        "packages": len({finding.package for finding in findings}),
        "by_urgency": Counter(finding.urgency for finding in findings),
        "by_status": Counter(finding.status for finding in findings),
        "by_package": Counter(finding.package for finding in findings),
    }
