#!/usr/bin/env python3
# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0
#
# Builds the vault image (OpenBao plus seine's plugins) for the
# 'seine-vault-openbao' package, same idea as build-oci.py. Needs
# network access to pull the golang/openbao base images.

import gzip
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)

from seine.container import ContainerEngine
from seine.utils import HOST_ARCH
from seine.vault.dev import CUSTOM_IMAGE, SOURCES_LABEL, _sources_digest

DOCKERFILE = os.path.join(HERE, "vault-image", "Dockerfile")

HOSTARCH = os.environ.get("HOSTARCH", HOST_ARCH)
REFRESH = os.environ.get("REFRESH") == "1"

LOCK_FILE = os.path.join(HERE, "debian", "build-vault-image.lock")


# Every 'FROM <image>' in the Dockerfile, so a new one is picked up
# here automatically.
def base_images():
    images = []
    with open(DOCKERFILE) as f:
        for line in f:
            parts = line.split()
            if len(parts) >= 2 and parts[0] == "FROM" and parts[1] not in images:
                images.append(parts[1])
    return images

# One "<image> <hostarch> <digest>" line per pinned base image, plain
# text so this needs no extra dependency to read.
def load_lock():
    lock = {}
    if not os.path.exists(LOCK_FILE):
        return lock
    with open(LOCK_FILE) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            image, arch, digest = line.split()
            lock[(image, arch)] = digest
    return lock

def save_lock(lock):
    with open(LOCK_FILE, "w") as f:
        f.write("# image arch digest -- generated by "
                 "'REFRESH=1 debian/build-vault-image.py', do not hand-edit\n")
        for (image, arch), digest in sorted(lock.items()):
            f.write("%s %s %s\n" % (image, arch, digest))

# The linux/<arch> digest from the registry's manifest list. A local
# pull's RepoDigests can't be trusted here: for these images it
# reports the same digest whatever --platform was asked for.
def manifest_digest(image, arch):
    out = ContainerEngine.check_output(["manifest", "inspect", image])
    manifest = json.loads(out)
    for entry in manifest.get("manifests", []):
        platform = entry.get("platform") or {}
        if platform.get("os") == "linux" and platform.get("architecture") == arch:
            return entry["digest"]
    raise RuntimeError("no linux/%s manifest for %s" % (arch, image))

# Pins 'image' to its locked digest, then retags it under its own
# name so the Dockerfile's FROM resolves locally, no registry hit.
def pin_base_image(image, lock):
    if REFRESH:
        lock[(image, HOSTARCH)] = manifest_digest(image, HOSTARCH)

    digest = lock.get((image, HOSTARCH))
    if digest is None:
        raise RuntimeError(
            "no pinned digest for %s/%s in %s -- run "
            "'HOSTARCH=%s REFRESH=1 debian/build-vault-image.py <out>' first"
            % (image, HOSTARCH, LOCK_FILE, HOSTARCH))
    ref = "%s@%s" % (image.rsplit(":", 1)[0], digest)
    ContainerEngine.run(["pull", ref], check=True)
    ContainerEngine.run(["tag", ref, image], check=True)

def main():
    out = os.path.join(sys.argv[1], "vault")
    os.makedirs(out, exist_ok=True)

    lock = load_lock()
    for image in base_images():
        pin_base_image(image, lock)
    if REFRESH:
        save_lock(lock)

    build = ["build", "--label",
              "%s=%s" % (SOURCES_LABEL, _sources_digest()),
              "-t", CUSTOM_IMAGE, "-f", DOCKERFILE]
    if HOSTARCH != HOST_ARCH:
        build += ["--platform", "linux/%s" % HOSTARCH]
    ContainerEngine.run(build + [HERE], check=True)

    with gzip.open(os.path.join(out, "images.tar.gz"), "wb",
                   compresslevel=1) as gz:
        podman = ContainerEngine.Popen(["save", CUSTOM_IMAGE],
                                       stdout=subprocess.PIPE)
        shutil.copyfileobj(podman.stdout, gz)
        podman.stdout.close()
        if podman.wait() != 0:
            raise RuntimeError("podman could not save %s!" % CUSTOM_IMAGE)

if __name__ == "__main__":
    main()
