#!/usr/bin/env python3
# seine - Slim Embedded Images Now Easy
# SPDX-License-Identifier: Apache-2.0
#
# Builds the OCI bundle a 'seine-oci-<release>' package ships (one
# HOSTARCH per dpkg-buildpackage run, via debian/rules): the plain
# 'debian:<release>' base image HostBootstrap (and the
# force_online=True HostBootstrap vendor.py builds) pull it FROM --
# the one and only podman/docker registry pull anywhere in seine's own
# container chain, everything else building FROM an already-local,
# seine-produced tag. Loaded into podman ahead of time (seine/oci_bundle.py),
# this is what lets seine never need a registry pull at all, on a real
# host matching HOSTARCH -- HostBootstrap's own apt-get/mmdebstrap work
# still runs for real, straight to the Debian archive, same as always.
# Not shipped in any package: run only at package-build time, straight
# from the checkout, never installed.
#
# Needs network access to pull 'debian:<release>', unlike a normal
# 'dpkg-buildpackage' run.
#
# HOSTARCH picks which host to pull for (default: this machine's own),
# via podman's own '--platform' -- so this runs the same on any machine,
# producing either host's bundle.
#
# For a build-reproducible release, the 'debian:<release>' tag is not
# enough by itself -- it moves as Debian pushes new point releases, so
# the same seine source can pick up a different base image months apart.
# LOCK_FILE (committed to git) pins the exact manifest digest pulled for
# each release/hostarch; a normal build always pulls by digest and never
# touches the floating tag. Run with REFRESH=1 to (re-)resolve the
# floating tag to today's digest and update LOCK_FILE.
#
# Usage: HOSTARCH=<arch> build-oci.py <output-dir>
#        HOSTARCH=<arch> REFRESH=1 build-oci.py <output-dir>

import gzip
import os
import shutil
import subprocess
import sys

RELEASES = os.environ.get("RELEASES", "bookworm trixie").split()
SOURCE = "debian"

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)

from seine.utils import ContainerEngine
from seine.utils import HOST_ARCH

HOSTARCH = os.environ.get("HOSTARCH", HOST_ARCH)
REFRESH = os.environ.get("REFRESH") == "1"

LOCK_FILE = os.path.join(HERE, "debian", "build-oci.lock")

# One "<release> <hostarch> <digest>" line per pinned image -- plain text
# rather than YAML so this script keeps zero extra runtime deps.
def load_lock():
    lock = {}
    if not os.path.exists(LOCK_FILE):
        return lock
    with open(LOCK_FILE) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            release, arch, digest = line.split()
            lock[(release, arch)] = digest
    return lock

def save_lock(lock):
    with open(LOCK_FILE, "w") as f:
        f.write("# release arch digest -- generated by "
                 "'REFRESH=1 debian/build-oci.py', do not hand-edit\n")
        for (release, arch), digest in sorted(lock.items()):
            f.write("%s %s %s\n" % (release, arch, digest))

def repo_digest(tag):
    out = ContainerEngine.check_output(
        ["image", "inspect", "-f", "{{index .RepoDigests 0}}", tag])
    return out.decode().strip().split("@", 1)[1]

def build_release(release, out, lock):
    tag = "%s:%s" % (SOURCE, release)
    pull = ["pull"]
    if HOSTARCH != HOST_ARCH:
        pull += ["--platform", "linux/%s" % HOSTARCH]

    if REFRESH:
        ContainerEngine.run(pull + [tag], check=True)
        lock[(release, HOSTARCH)] = repo_digest(tag)
    else:
        digest = lock.get((release, HOSTARCH))
        if digest is None:
            raise RuntimeError(
                "no pinned digest for %s/%s in %s -- run "
                "'HOSTARCH=%s REFRESH=1 debian/build-oci.py <out>' first"
                % (release, HOSTARCH, LOCK_FILE, HOSTARCH))
        ref = "%s@%s" % (SOURCE, digest)
        ContainerEngine.run(pull + [ref], check=True)
        ContainerEngine.run(["tag", ref, tag], check=True)

    release_out = os.path.join(out, release)
    os.makedirs(release_out, exist_ok=True)
    with gzip.open(os.path.join(release_out, "images.tar.gz"), "wb",
                   compresslevel=1) as gz:
        podman = ContainerEngine.Popen(["save", tag], stdout=subprocess.PIPE)
        shutil.copyfileobj(podman.stdout, gz)
        podman.stdout.close()
        if podman.wait() != 0:
            raise RuntimeError("podman could not save %s!" % tag)

def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)

    print("building for: host %s, releases %s%s" % (
        HOSTARCH, RELEASES, " (REFRESH)" if REFRESH else ""))
    lock = load_lock()
    for release in RELEASES:
        build_release(release, out, lock)
    if REFRESH:
        save_lock(lock)

if __name__ == "__main__":
    main()
